FROM rust:slim-bookworm AS base

RUN apt-get update && apt-get install -y --no-install-recommends make \
    curl jq python3 ca-certificates pkg-config libssl-dev nodejs npm \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install wasm-pack \
    && rustup target add wasm32-unknown-unknown

RUN rustc --version && wasm-pack --version

WORKDIR /tutorials
CMD ["bash"]
