describe("metrics", function()
    local metrics = require("src.metrics")

    before_each(function()
        metrics.reset()
    end)

    it("counter_inc increments value", function()
        metrics.counter_inc("http_requests_total")
        metrics.counter_inc("http_requests_total")
        assert.are.equal(2, metrics.counter_get("http_requests_total"))
    end)

    it("counter_inc increments by custom value", function()
        metrics.counter_inc("bytes_total", 512)
        assert.are.equal(512, metrics.counter_get("bytes_total"))
    end)

    it("counter_get returns 0 for unknown", function()
        assert.are.equal(0, metrics.counter_get("nonexistent"))
    end)

    it("format() contains counter name", function()
        metrics.counter_inc("test_total", 5)
        local output = metrics.format()
        assert.truthy(output:find("test_total"))
        assert.truthy(output:find("# TYPE test_total counter"))
    end)

    it("histogram_observe records values", function()
        metrics.histogram_observe("request_duration", 0.1)
        metrics.histogram_observe("request_duration", 0.2)
        local output = metrics.format()
        assert.truthy(output:find("request_duration_count 2"))
    end)

    it("format() contains histogram sum and count", function()
        metrics.histogram_observe("latency", 1.5)
        metrics.histogram_observe("latency", 2.5)
        local output = metrics.format()
        assert.truthy(output:find("latency_sum 4"))
        assert.truthy(output:find("latency_count 2"))
        assert.truthy(output:find("# TYPE latency histogram"))
    end)

    it("reset() clears all metrics", function()
        metrics.counter_inc("a_total", 10)
        metrics.histogram_observe("b_duration", 1.0)
        metrics.reset()
        assert.are.equal(0, metrics.counter_get("a_total"))
        assert.are.equal("", metrics.format():gsub("%s+", ""))
    end)
end)
