package.path = "src/?.lua;" .. package.path
local cli = require("hello_cli")

describe("hello_cli", function()
    describe("parse_args", function()
        it("parses --name", function()
            local opts = cli.parse_args({"--name", "Alice"})
            assert.equals("Alice", opts.name)
        end)
        it("parses --shout", function()
            local opts = cli.parse_args({"--shout"})
            assert.is_true(opts.shout)
        end)
        it("uses defaults", function()
            local opts = cli.parse_args({})
            assert.equals("world", opts.name)
            assert.is_false(opts.shout)
        end)
        it("parses --name and --shout together", function()
            local opts = cli.parse_args({"--name", "Bob", "--shout"})
            assert.equals("Bob", opts.name)
            assert.is_true(opts.shout)
        end)
    end)
    describe("format", function()
        it("formats normal greeting", function()
            assert.equals("Hello, Alice!", cli.format({name="Alice", shout=false}))
        end)
        it("formats shouted greeting", function()
            assert.equals("HELLO, ALICE!", cli.format({name="Alice", shout=true}))
        end)
        it("formats default greeting", function()
            assert.equals("Hello, world!", cli.format({name="world", shout=false}))
        end)
    end)
end)
