FROM rust:slim-bookworm AS base

RUN apt-get update && apt-get install -y --no-install-recommends make \
    curl jq python3 ca-certificates pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustc --version && cargo --version

WORKDIR /tutorials
CMD ["bash"]
