local server = require("src.server")

describe("server", function()
    it("GET / returns 200 with hello world", function()
        local status, body = server.handle_request("GET / HTTP/1.1")
        assert.equals(200, status)
        assert.truthy(body:find("Hello, world!"))
    end)
    it("GET /greet/Alice returns greeting", function()
        local status, body = server.handle_request("GET /greet/Alice HTTP/1.1")
        assert.equals(200, status)
        assert.truthy(body:find("Hello, Alice!"))
    end)
    it("GET /unknown returns 404", function()
        local status, _ = server.handle_request("GET /unknown HTTP/1.1")
        assert.equals(404, status)
    end)
    it("bad request returns 400", function()
        local status, _ = server.handle_request("")
        assert.equals(400, status)
    end)
    it("format_response builds HTTP response", function()
        local resp = server.format_response(200, '{"ok":true}')
        assert.truthy(resp:find("HTTP/1.1 200 OK"))
        assert.truthy(resp:find("Content%-Type: application/json"))
        assert.truthy(resp:find('{"ok":true}'))
    end)
end)
