local json = require("dkjson")
local logger = require("src.logger")

describe("logger", function()
    describe("info", function()
        it("returns valid JSON", function()
            local output = logger.info("hello")
            local decoded, _, err = json.decode(output)
            assert.is_nil(err)
            assert.is_not_nil(decoded)
        end)

        it("has message, level, and timestamp keys", function()
            local output = logger.info("test message")
            local decoded = json.decode(output)
            assert.are.equal("test message", decoded.message)
            assert.are.equal("info", decoded.level)
            assert.is_not_nil(decoded.timestamp)
        end)

        it("includes metadata fields", function()
            local output = logger.info("with meta", {user = "alice", request_id = 42})
            local decoded = json.decode(output)
            assert.are.equal("alice", decoded.user)
            assert.are.equal(42, decoded.request_id)
        end)
    end)

    describe("levels", function()
        it("warn produces level warn", function()
            local output = logger.warn("caution")
            local decoded = json.decode(output)
            assert.are.equal("warn", decoded.level)
        end)

        it("error produces level error", function()
            local output = logger.error("failure")
            local decoded = json.decode(output)
            assert.are.equal("error", decoded.level)
        end)

        it("info produces level info", function()
            local output = logger.info("notice")
            local decoded = json.decode(output)
            assert.are.equal("info", decoded.level)
        end)
    end)

    describe("timestamp", function()
        it("has ISO 8601 format", function()
            local output = logger.info("ts test")
            local decoded = json.decode(output)
            assert.is_truthy(decoded.timestamp:match("^%d%d%d%d%-%d%d%-%d%dT%d%d:%d%d:%d%dZ$"))
        end)
    end)
end)
