describe("health_checker", function()
    local health = require("src.health_checker")
    local json = require("dkjson")

    before_each(function()
        health.init()
    end)

    it("init sets deps to ok", function()
        local all = health.check_all()
        assert.are.equal("ok", all.database)
        assert.are.equal("ok", all.cache)
    end)

    it("status() returns ok initially", function()
        assert.are.equal("ok", health.status())
    end)

    it("status is degraded after set_dependency error", function()
        health.set_dependency("database", "error")
        assert.are.equal("degraded", health.status())
    end)

    it("check_all returns full map", function()
        health.set_dependency("database", "error")
        local all = health.check_all()
        assert.are.equal("error", all.database)
        assert.are.equal("ok", all.cache)
    end)

    it("liveness_json returns valid JSON with status ok", function()
        local body = health.liveness_json()
        local decoded = json.decode(body)
        assert.are.equal("ok", decoded.status)
    end)

    it("readiness_json returns 503 when degraded", function()
        health.set_dependency("cache", "error")
        local body, code = health.readiness_json()
        assert.are.equal(503, code)
        local decoded = json.decode(body)
        assert.are.equal("degraded", decoded.status)
    end)

    it("readiness_json returns 200 when ok", function()
        local body, code = health.readiness_json()
        assert.are.equal(200, code)
        local decoded = json.decode(body)
        assert.are.equal("ok", decoded.status)
    end)

    it("health_json includes checks", function()
        health.set_dependency("database", "error")
        local body = health.health_json()
        local decoded = json.decode(body)
        assert.are.equal("degraded", decoded.status)
        assert.are.equal("error", decoded.checks.database.status)
        assert.are.equal("ok", decoded.checks.cache.status)
    end)
end)
