describe("openapi_spec", function()
    local spec_mod = require("src.openapi_spec")
    local json = require("dkjson")

    it("spec() has openapi key", function()
        local s = spec_mod.spec()
        assert.are.equal("3.0.0", s.openapi)
    end)

    it("spec() has paths with /api/greet", function()
        local s = spec_mod.spec()
        assert.is_not_nil(s.paths["/api/greet"])
        assert.is_not_nil(s.paths["/api/greet"].get)
    end)

    it("to_json() returns valid JSON", function()
        local output = spec_mod.to_json()
        local decoded, _, err = json.decode(output)
        assert.is_nil(err)
        assert.is_not_nil(decoded)
        assert.are.equal("3.0.0", decoded.openapi)
    end)

    it("validate_name with valid name returns name", function()
        local result, err = spec_mod.validate_name("Alice")
        assert.are.equal("Alice", result)
        assert.is_nil(err)
    end)

    it("validate_name with nil returns nil + error", function()
        local result, err = spec_mod.validate_name(nil)
        assert.is_nil(result)
        assert.are.equal("name parameter is required", err)
    end)

    it("validate_name with empty string returns nil + error", function()
        local result, err = spec_mod.validate_name("")
        assert.is_nil(result)
        assert.are.equal("name parameter is required", err)
    end)
end)
