FROM golang:1.23-bookworm AS base

RUN apt-get update && apt-get install -y --no-install-recommends make \
    curl jq python3 ca-certificates lsof \
    && rm -rf /var/lib/apt/lists/*

RUN go version

WORKDIR /tutorials
CMD ["bash"]
